### PR TITLE
Fix setup error on windows environment

### LINKED ISSUE #9: Cannot install lwc/rest/jest
Trying to install via cli setup:

>sfdx force:lightning:lwc:test:setup --loglevel debug
ERROR running force:lightning:lwc:test:setup:  npm command not found. Verify npm is properly installed and try again.

Running npm shows:
npm@6.9.0 C:\Program Files\nodejs\node_modules\npm

### PR DESCRIPTION
**Pull request by pmdartus**
Fixes #9, discussion about the approach fixing this issue can be found in the issue thread.

### CODE REVIEW

File: src/commands/force/lightning/lwc/test/run.ts [hunk 1]
```diff
@@ -70,7 +70,10 @@ export default class Run extends SfdxCommand {
   }
 
   private runJest(args) {
-    return spawnSync(this.getExecutablePath(), args, { stdio: 'inherit' });
+    return spawnSync(this.getExecutablePath(), args, {
```
Comment (pmdartus) [inline src/commands/force/lightning/lwc/test/run.ts:73]: I decided to keep the `spawnSync` here since we are interested in the status code to report back to the user. Adding the `shell` flag to make sure the node can be resolved.

**Comment by pmdartus** [comment]
To avoid running into similar issues in the future, it would be great to run some smoke tests as part of the CI for both lunix and windows environments. Something like:
- create a new SFDX project
- setup the project
- run a component test

File: test/commands/lwc/test/setup.test.ts [hunk 2]
```diff
@@ -359,11 +362,11 @@ describe('force:lightning:lwc:test:setup', () => {
     test
     .do(() => {
       stubMethod($$.SANDBOX, child_process, 'spawnSync').callsFake(cmd => {
-        if (cmd === 'node') {
-          return { status: 0, stdout: 'v8.12.0' };
+        if (cmd === 'node -v') {
```
Comment (ravijayaramappa) [inline test/commands/lwc/test/setup.test.ts:365]: missed replacing `spawnSync` for this testcase I think, unless it was intentional.

File: test/commands/lwc/test/setup.test.ts [hunk 3]
```diff
@@ -290,11 +293,11 @@ describe('force:lightning:lwc:test:setup', () => {
     test
     .do(() => {
       stubMethod($$.SANDBOX, child_process, 'spawnSync').callsFake(cmd => {
```
Comment (ravijayaramappa) [inline test/commands/lwc/test/setup.test.ts:295]:
```suggestion
      stubMethod($$.SANDBOX, child_process, 'execSync').callsFake(cmd => {
```

File: test/commands/lwc/test/setup.test.ts (hunk 2 above)
Comment (pmdartus) [reply test/commands/lwc/test/setup.test.ts:365]: I found this issue, this is because when not mocked, the `spawnSync` method is invoked and executes the real command which returns the current node version installed on the machine.

**Comment by pmdartus** [comment]
@trevor-bliss I am not familiar with the release process of SFDX plugin. Is releasing a new version to NPM sufficient? Or anything else needs to be done to make the new release available.

**Comment by trevor-bliss** [comment]
We'll need help from the SFDX devops folks to make sure it gets integrated into the core CLI. I'll ping them separately.

**Comment by hongda-zhou** [comment]
image

Is there a solution for this error yet?
